name: CI / Build & Test (web+api)

on:
  pull_request:
    branches: [ main ]
  # 필요하면 push도 함께 트리거
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Monorepo는 루트에서 한 번만 설치
      - name: Install deps (root)
        run: npm ci

      # --- API ---
      - name: Typecheck (api)
        run: npm -w apps/api run typecheck

      - name: Test (api)
        run: npm -w apps/api run test --if-present

      - name: Build (api)
        run: npm -w apps/api run build

      # --- WEB ---
      - name: Typecheck (web)
        run: npm -w apps/web run typecheck --if-present

      - name: Build (web)
        run: npm -w apps/web run build
        env:
          # 필요 시 빌드 타임 환경변수 주입
          VITE_API_BASE: http://localhost:8787