name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test (web+api)
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ---------- API ----------
      - name: Install deps (api)
        working-directory: apps/api
        run: npm ci || npm install --no-audit --no-fund

      - name: Typecheck (api)
        working-directory: apps/api
        run: npm run typecheck

      - name: Test (api)
        working-directory: apps/api
        env:
          NODE_ENV: test
        run: npm test --silent

      - name: Build (api)
        working-directory: apps/api
        run: npm run build

      # ---------- WEB ----------
      - name: Install deps (web)
        working-directory: apps/web
        run: npm ci || npm install --no-audit --no-fund

      - name: Typecheck (web)
        working-directory: apps/web
        run: npm run typecheck || echo "no typecheck script"

      - name: Build (web)
        working-directory: apps/web
        run: npm run build